- name: Install packages
  import_role:
    name: common_roles/install_latest
  vars:
    packages: "cron"

- name: Monthly updates
  cron:
    name: update nextcloud
    state: present
    minute: "0"
    hour: "0"
    day: "1"
    job: >
      /usr/bin/docker stop {{ container }};
      /usr/bin/docker rm {{ container }};
      /usr/bin/docker pull {{ image }};
      /usr/bin/docker run -d
      --restart unless-stopped
      --name {{ container }}
      --env-file /home/{{ username }}/docker_env_files/{{ service.cloud.subdomain }}.env
      -v {{ data_dir }}/data/:/var/www/html/data/
      -v {{ data_dir }}/apps/:/var/www/html/apps/
      -v {{ data_dir }}/config/:/var/www/html/config/
      -p {{ service.cloud.port }}:80
      {{ image }};
      while [ "$(docker inspect -f '{{ '{{ .State.Running }}' }}' {{ container }})" != "true" ]; do sleep 1; done;
      docker exec --user www-data {{ container }} php occ upgrade --no-interaction

- name: Backup
  block:
    - name: Mkdir backup_dir
      file:
        state: directory
        path: "{{ backup_dir }}"
        mode: 0755

    - name: Weekly backups
      cron:
        name: "backup cloud"
        state: "present"
        special_time: "weekly"
        job: >
          sudo /bin/cp -urp {{ data_dir }}/* {{ backup_dir }}

- name: Enable auto-refresh with Cron
  cron:
    name: "cloud - cron"
    state: "present"
    minute: "*/5"
    job: >
      /usr/bin/docker exec -u www-data {{ container }} /bin/sh -c 'php -f /var/www/html/cron.php'
