- name: Admin Token
  block:
    - name: Install packages
      import_role:
        name: common_roles/install_latest
      vars:
        packages: "argon2"

    - name: Create admin admin_token
      shell:
        cmd: |
          set -o pipefail
          echo -n "{{ vaultwarden_password }}" | argon2 "$(openssl rand -base64 32)" -e -id -k 65540 -t 3 -p 4
        executable: /bin/bash
      register: admin_token
      changed_when: true

- name: Setup docker
  tags: ignore-ci # ci doesn't boot with systemd
  import_role:
    name: common_roles/docker

- name: Mkdir docker_env_files
  file:
    state: directory
    path: "/home/{{ username }}/docker_env_files"
    mode: 0755

- name: Docker env file
  copy:
    dest: "/home/{{ username }}/docker_env_files/{{ service.vault.subdomain }}.env"
    content: |
      ADMIN_TOKEN={{ admin_token.stdout }}
      SIGNUPS_ALLOWED=false
    mode: 0644
