- name: Clean up docker
  cron:
    name: docker prune
    state: present
    minute: "0"
    hour: "0"
    day: "2"
    job: "docker system prune --force --all --volumes"

- name: Clean up journalctl
  lineinfile:
    path: "/etc/systemd/journald.conf"
    line: "MaxRetentionSec=2day"
    insertafter: EOF
