- name: Secure ssh config
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    validate: "sshd -T -f %s"
    mode: 0644
  with_items:
    - regexp: "^#?PasswordAuthentication.*"
      line: "PasswordAuthentication no"
    - regexp: "^#?PermitRootLogin.*"
      line: "PermitRootLogin no"
    - regexp: "^#?Port.*"
      line: "Port {{ ports.ssh }}"
    - regexp: "^#?PermitEmptyPasswords.*"
      line: "PermitEmptyPasswords no"
    - regexp: "^#?X11Forwarding.*"
      line: "X11Forwarding no"
    - regexp: "^#?MaxAuthTries.*"
      line: "MaxAuthTries 3"

- name: Enable and restart ssh
  service:
    name: sshd
    enabled: true
    state: restarted
